# Generated by Django 3.1.1 on 2020-10-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201021_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasd', to='api.miembro_proyecto'),
        ),
    ]
