# Generated by Django 3.1.1 on 2020-10-21 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20201021_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='user',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocolo_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
