# Generated by Django 3.1.1 on 2020-11-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro_proyecto',
            name='name',
        ),
        migrations.AddField(
            model_name='miembro_proyecto',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembro_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
