# Generated by Django 3.1.3 on 2020-12-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0005_auto_20201201_1528'),
        ('localapp', '0003_auto_20201129_1129'),
    ]

    operations = [
    ]
