# Generated by Django 3.1.3 on 2020-12-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0006_merge_20201203_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='actual',
            field=models.IntegerField(default=1),
        ),
    ]
