# Generated by Django 3.1.1 on 2020-10-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='name1',
            new_name='name',
        ),
    ]
