# Generated by Django 3.1.1 on 2020-10-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201017_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolo',
            old_name='state',
            new_name='status',
        ),
    ]
