# Generated by Django 3.1.1 on 2020-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201202_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='actual',
            field=models.IntegerField(default=1),
        ),
    ]
